In [1]:
# import libraries
import pandas as pd

In [2]:
# read a CSV format text file
# the data is sorted by utc_time
df = pd.read_csv('beijing_air_quality_data.csv',
                 parse_dates=['utc_time'])

In [3]:
# for temperature and humidity
# calculate its mean, standard deviation
df_mean = df.mean()
df_sd = df.std(axis = 0)
print(df_mean)
print(df_sd)

epoch_time         1.526427e+09
lat                3.998714e+01
lon                1.164057e+02
pm25               5.893740e+01
pm10               1.278878e+02
no2                4.237323e+01
co                 7.047478e-01
o3                 9.368241e+01
so2                5.430204e+00
temperature        2.195770e+01
pressure           9.933121e+02
humidity           3.577648e+01
wind_direction     1.672238e+02
wind_speed_kmph    9.403533e+00
dtype: float64
epoch_time         897909.383745
lat                     0.230513
lon                     0.281808
pm25                   43.684511
pm10                  101.799565
no2                    28.338347
co                      0.456998
o3                     64.517506
so2                     5.908053
temperature             5.416088
pressure               17.858515
humidity               19.158965
wind_direction         85.114877
wind_speed_kmph         5.292269
dtype: float64

In [4]:
# how many unique site_id?
# Hint: check pd.unique method
noOfUniqueSite_id = len(pd.unique(df.site_id))
noOfUniqueSite_id

35

In [5]:
# what is the range of utc_time?
# Hint: you can call min() and max() for the utc_time column
df_max = df.utc_time.max()
df_min = df.utc_time.min()
rangeOfUtc_time = df_max - df_min
rangeOfUtc_time

Timedelta('35 days 23:00:00')

In [6]:
# for pm25, fill NAs with mean value
mean_pm25 = df.pm25.mean()
df['pm25'].fillna(mean_pm25, inplace=True)

df

,site_id,utc_time,epoch_time,lat,lon,sitetype,pm25,pm10,no2,co,o3,so2,weather,temperature,pressure,humidity,wind_direction,wind_speed_kmph
0,dongsi_aq,2018-04-28 00:00:00,1524873600,39.93,116.42,Urban Stations,59.000000,172.0,96.0,0.8,8.0,5.0,CLEAR_DAY,17.03,1006.54,40.47,101.19,2.77
1,tiantan_aq,2018-04-28 00:00:00,1524873600,39.89,116.41,Urban Stations,52.000000,187.0,104.0,0.8,3.0,5.0,CLEAR_DAY,17.09,1006.78,40.85,104.62,2.34
2,guanyuan_aq,2018-04-28 00:00:00,1524873600,39.93,116.34,Urban Stations,54.000000,165.0,91.0,0.6,13.0,7.0,CLEAR_DAY,17.24,1004.53,40.50,89.65,2.86
3,wanshouxigong_aq,2018-04-28 00:00:00,1524873600,39.88,116.35,Urban Stations,51.000000,184.0,93.0,0.9,6.0,5.0,CLEAR_DAY,17.30,1005.60,40.86,102.21,2.46
4,aotizhongxin_aq,2018-04-28 00:00:00,1524873600,39.98,116.40,Urban Stations,58.000000,134.0,86.0,0.7,6.0,3.0,CLEAR_DAY,16.98,1005.89,39.64,82.69,3.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30235,qianmen_aq,2018-06-02 23:00:00,1527980400,39.90,116.39,Stations Near Traffic,58.937398,NaN,NaN,NaN,NaN,NaN,CLOUDY,23.38,1002.15,27.19,25.17,4.48
30236,yongdingmennei_aq,2018-06-02 23:00:00,1527980400,39.88,116.39,Stations Near Traffic,58.937398,NaN,NaN,NaN,NaN,NaN,CLOUDY,23.91,1002.20,27.43,63.47,4.21
30237,xizhimenbei_aq,2018-06-02 23:00:00,1527980400,39.95,116.35,Stations Near Traffic,58.937398,NaN,NaN,NaN,NaN,NaN,CLOUDY,24.08,999.61,28.76,6.12,6.62
30238,nansanhuan_aq,2018-06-02 23:00:00,1527980400,39.86,116.37,Stations Near Traffic,58.937398,NaN,NaN,NaN,NaN,NaN,CLOUDY,24.03,1002.18,27.55,96.77,3.62
30239,dongsihuan_aq,2018-06-02 23:00:00,1527980400,39.94,116.48,Stations Near Traffic,58.937398,NaN,NaN,NaN,NaN,NaN,CLOUDY,24.10,1003.36,28.31,78.99,4.61

In [7]:
# select data for a station where site_id equals to dongsi_aq
dongsi_df = df[df['site_id'] == 'dongsi_aq']

dongsi_df_pm25 = dongsi_df['pm25']

# calculate the mean value of pm25 at this station
mean_dongsi_df_pm25 = dongsi_df_pm25.mean()

# calculate how many data points when pm25 >= 50 at this station
seriesObj = df.apply(lambda x: True if x['pm25'] >= 50 
                     and x['site_id'] == 'dongsi_aq' else False,axis=1)
numOfDataPoints = len(seriesObj[seriesObj == True].index)
numOfDataPoints
# Hint: check count() method

491

In [8]:
# how many NAs for pm25 values at this station
# Hint: check isnull() method
dongsi_df_pm25.isnull().sum()

0